name: SlabboMaps
description: Google Maps for your shopping district
version: '${version}'
main: gg.mew.plugins.slabbomaps.SlabboMaps
api-version: '1.20'
author: Maarten Vos
website: https://git.sr.ht/~inferiormartin/slabbo-maps
permissions:
  slabbomaps.reload:
    description: Allows for the reloading of Slabbo's shops.yml file
  slabbomaps.locate.item:
    description: Allows for locating a shop selling/buying a specific item
    default: true
depend:
  - Slabbo
softdepend:
  - Lands
